name: PortalAnnouncer
version: 1.0
author: Zero
main: io.github.animeavi.portalannouncer.PortalAnnouncer

commands:
  pareload:
    Description: Reloads the configuration file
    usage: /pareload
    permission: pa.reload

permissions:
  pa.reload:
    description: Allows player to reload the config file for PortalAnnouncer
    default: op
